[package]
name = "kickdosage/vide-fixed"
description = "A fork of centau's vide."
license = "MIT"
version = "0.4.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "LICENSE", "src"]
exclude = [
    ".github",
	"test",
	".gitattributes",
	".gitignore",
    ".luaurc",
	"CHANGELOG.md",
	"README.md",
    "todo.md"
]
